In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('customer.csv')
df.sample(5)

    age  gender   review education purchased
30   73    Male  Average        UG        No
35   74    Male     Poor    School       Yes
25   57  Female     Good    School        No
19   97    Male     Poor        PG       Yes
11   74    Male     Good        UG       Yes

In [4]:
df.shape

(50, 5)

In [5]:
df=df.iloc[:,2:]
df.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
X_train

     review education
38     Good    School
48     Good        UG
16     Poor        UG
22     Poor        PG
12     Poor    School
36     Good        UG
46     Poor        PG
44  Average        UG
9      Good        UG
19     Poor        PG
29  Average        UG
31     Poor    School
13  Average    School
45     Poor        PG
15     Poor        UG
5   Average    School
11     Good        UG
0   Average    School
20  Average    School
7      Poor    School
40     Good    School
30  Average        UG
8   Average        UG
3      Good        PG
26     Poor        PG
21  Average        PG
14     Poor        PG
41     Good        PG
49     Good        UG
33     Good        PG
2      Good        PG
32  Average        UG
24  Average        PG
6      Good    School
47     Good        PG
39     Poor        PG
35     Poor    School
1      Poor        UG
18     Good    School
17     Poor        UG

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
X_train = oe.fit_transform(X_train)
X_train

array([[2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [0., 1.]])

In [10]:
hello=pd.DataFrame(X_train,columns=["grade",'Education'])
hello

    grade  Education
0     2.0        0.0
1     2.0        1.0
2     0.0        1.0
3     0.0        2.0
4     0.0        0.0
5     2.0        1.0
6     0.0        2.0
7     1.0        1.0
8     2.0        1.0
9     0.0        2.0
10    1.0        1.0
11    0.0        0.0
12    1.0        0.0
13    0.0        2.0
14    0.0        1.0
15    1.0        0.0
16    2.0        1.0
17    1.0        0.0
18    1.0        0.0
19    0.0        0.0
20    2.0        0.0
21    1.0        1.0
22    1.0        1.0
23    2.0        2.0
24    0.0        2.0
25    1.0        2.0
26    0.0        2.0
27    2.0        2.0
28    2.0        1.0
29    2.0        2.0
30    2.0        2.0
31    1.0        1.0
32    1.0        2.0
33    2.0        0.0
34    2.0        2.0
35    0.0        2.0
36    0.0        0.0
37    0.0        1.0
38    2.0        0.0
39    0.0        1.0

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

Y_train=le.fit_transform(Y_train)
Y_test=le.fit_transform(Y_test)

hi=pd.DataFrame(Y_test)
hello=pd.DataFrame(Y_train)


hi

   0
0  0
1  1
2  0
3  0
4  0
5  0
6  1
7  0
8  0
9  1

In [12]:
hello

    0
0   0
1   1
2   1
3   1
4   0
5   1
6   0
7   0
8   1
9   1
10  1
11  1
12  0
13  1
14  0
15  1
16  1
17  0
18  1
19  1
20  0
21  0
22  0
23  0
24  0
25  0
26  1
27  1
28  0
29  1
30  0
31  1
32  1
33  0
34  1
35  0
36  1
37  0
38  0
39  1