In [2]:
import numpy as np
import pandas as pd

In [3]:
date=pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [7]:
date['date'] = pd.to_datetime(date['date'])

In [13]:
date.sample(5)

          date  product_id  city_id  orders
776 2019-08-18         704       13      10
481 2019-02-16        1115       30       1
781 2019-10-12        7425       22       9
134 2019-11-17        6049       16       1
161 2019-03-30        7140       18      26

In [21]:
date['year']=date['date'].dt.year

In [17]:
date['month']=date['date'].dt.month

In [23]:
date.head(5)

        date  product_id  city_id  orders  month  days  year
0 2019-12-10        5628       25       3     12  2019  2019
1 2018-08-15        3646       14     157      8  2018  2018
2 2018-10-23        1859       25       1     10  2018  2018
3 2019-08-17        7292       25       1      8  2019  2019
4 2019-01-06        4344       25       3      1  2019  2019

In [32]:
date.sample(5)

          date  product_id  city_id  orders  month  year
984 2019-11-23         528        0       3     11  2019
287 2018-12-15        6368       25       1     12  2018
13  2018-08-24        3020       13       4      8  2018
924 2018-09-01        1484        3      19      9  2018
100 2018-11-22        6343       22     191     11  2018

In [ ]:
date['days']=date['date'].dt.day_of_year

In [89]:
date.head(5)

,date,product_id,city_id,orders,month,year,days,weekend,day_of_the_week
0,2019-12-10,5628,25,3,12,2019,344,0,1
1,2018-08-15,3646,14,157,8,2018,227,0,2
2,2018-10-23,1859,25,1,10,2018,296,0,1
3,2019-08-17,7292,25,1,8,2019,229,0,5
4,2019-01-06,4344,25,3,1,2019,6,0,6

In [52]:
date['day_of_the_week']=date['date'].dt.day_of_week

In [54]:
date['weekend']=np.where(date['day_of_the_week'].isin(['Sunday','Saturday']),1,0)

In [137]:
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2026, 6, 10, 12, 43, 29, 958215)