In [53]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [54]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [55]:
X=df.iloc[:,1:3]
y=df['Survived']

In [56]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [57]:
X_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [58]:
si = SimpleImputer()
X_train_missing = si.fit_transform(X_train)
X_test_missing = si.transform(X_test)

In [59]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train_missing,y_train)
y_pred=lr.predict(X_test_missing)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

In [65]:
from sklearn.impute import MissingIndicator
mi = MissingIndicator()
X_train_missinggg = mi.fit_transform(X_train)
X_test_missinggg = mi.transform(X_test)
X_train['Age_Na']=X_train_missinggg
X_train

ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Age_Na